# Generated by Django 4.1.6 on 2023-02-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soccer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_data', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField()),
                ('player_name', models.CharField(max_length=100)),
                ('player_id', models.IntegerField()),
                ('player_tshirt_number', models.IntegerField()),
            ],
        ),
    ]
